#Write a program that takes an array as input from the user and find out the product of the elements. 
#Note: You have to complete Find_Prod. No need to take any input. 

x= [1,2,3,4,5]
prod = 1 
for n in x :
     prod = n* prod 
print("total product is :" , prod)

# Q2. Find the Sum. 
#Write a program which takes an array as input from the user and find out the sum of the array elements. 
#Note: You have to complete Find_Sum. No need to take any input.

x= [1,2,3,4,5]
sum = 0
for n in x :
    sum = n + sum 
print("total sum is :" , sum)

#Q3. Count Occurrences 
#You are given an array A containing N integer elements and an integer K, and your task is to return the count of 
#occurrences of K in array A.




